# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui\layout.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Inservency(object):
    def setupUi(self, Inservency):
        Inservency.setObjectName("Inservency")
        Inservency.resize(796, 530)
        self.centralwidget = QtWidgets.QWidget(Inservency)
        self.centralwidget.setMinimumSize(QtCore.QSize(796, 0))
        self.centralwidget.setAutoFillBackground(False)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.mainTabs = QtWidgets.QTabWidget(self.centralwidget)
        self.mainTabs.setObjectName("mainTabs")
        self.basicSetup = QtWidgets.QWidget()
        self.basicSetup.setObjectName("basicSetup")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.basicSetup)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.formLayout.setFieldGrowthPolicy(QtWidgets.QFormLayout.ExpandingFieldsGrow)
        self.formLayout.setLabelAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.formLayout.setContentsMargins(5, -1, 100, -1)
        self.formLayout.setVerticalSpacing(10)
        self.formLayout.setObjectName("formLayout")
        self.serverNameLabel = QtWidgets.QLabel(self.basicSetup)
        self.serverNameLabel.setIndent(10)
        self.serverNameLabel.setObjectName("serverNameLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.serverNameLabel)
        self.serverNameEdit = QtWidgets.QLineEdit(self.basicSetup)
        self.serverNameEdit.setObjectName("serverNameEdit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.serverNameEdit)
        self.queryPortLabel = QtWidgets.QLabel(self.basicSetup)
        self.queryPortLabel.setIndent(10)
        self.queryPortLabel.setOpenExternalLinks(False)
        self.queryPortLabel.setObjectName("queryPortLabel")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.queryPortLabel)
        self.passwordLabel = QtWidgets.QLabel(self.basicSetup)
        self.passwordLabel.setScaledContents(False)
        self.passwordLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.passwordLabel.setObjectName("passwordLabel")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.passwordLabel)
        self.maxPlayersLabel = QtWidgets.QLabel(self.basicSetup)
        self.maxPlayersLabel.setObjectName("maxPlayersLabel")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.maxPlayersLabel)
        self.cheatsLabel = QtWidgets.QLabel(self.basicSetup)
        self.cheatsLabel.setObjectName("cheatsLabel")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.cheatsLabel)
        self.motdLabel = QtWidgets.QLabel(self.basicSetup)
        self.motdLabel.setObjectName("motdLabel")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.motdLabel)
        self.gamePortInput = QtWidgets.QSpinBox(self.basicSetup)
        self.gamePortInput.setMinimumSize(QtCore.QSize(60, 0))
        self.gamePortInput.setFrame(True)
        self.gamePortInput.setPrefix("")
        self.gamePortInput.setMaximum(99999)
        self.gamePortInput.setProperty("value", 27102)
        self.gamePortInput.setObjectName("gamePortInput")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.gamePortInput)
        self.queryPortInput = QtWidgets.QSpinBox(self.basicSetup)
        self.queryPortInput.setMinimumSize(QtCore.QSize(60, 0))
        self.queryPortInput.setMaximum(99999)
        self.queryPortInput.setProperty("value", 27131)
        self.queryPortInput.setObjectName("queryPortInput")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.queryPortInput)
        self.passwordEdit = QtWidgets.QLineEdit(self.basicSetup)
        self.passwordEdit.setObjectName("passwordEdit")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.passwordEdit)
        self.maxPlayersEdit = QtWidgets.QSpinBox(self.basicSetup)
        self.maxPlayersEdit.setMinimum(1)
        self.maxPlayersEdit.setMaximum(28)
        self.maxPlayersEdit.setProperty("value", 28)
        self.maxPlayersEdit.setObjectName("maxPlayersEdit")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.maxPlayersEdit)
        self.checkBox = QtWidgets.QCheckBox(self.basicSetup)
        self.checkBox.setObjectName("checkBox")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.checkBox)
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.basicSetup)
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.plainTextEdit)
        self.gamePortLabel = QtWidgets.QLabel(self.basicSetup)
        self.gamePortLabel.setIndent(10)
        self.gamePortLabel.setObjectName("gamePortLabel")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.gamePortLabel)
        self.verticalLayout_2.addLayout(self.formLayout)
        self.mainTabs.addTab(self.basicSetup, "")
        self.maps = QtWidgets.QWidget()
        self.maps.setObjectName("maps")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.maps)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.mapsContainer = QtWidgets.QHBoxLayout()
        self.mapsContainer.setObjectName("mapsContainer")
        self.scrollArea = QtWidgets.QScrollArea(self.maps)
        self.scrollArea.setMaximumSize(QtCore.QSize(9999999, 16777215))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 609, 396))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.scenarioTreeView = QtWidgets.QTreeView(self.scrollAreaWidgetContents)
        self.scenarioTreeView.setObjectName("scenarioTreeView")
        self.verticalLayout_6.addWidget(self.scenarioTreeView)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(-1, 10, -1, -1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.startingMapLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.startingMapLabel.setMinimumSize(QtCore.QSize(70, 0))
        self.startingMapLabel.setMaximumSize(QtCore.QSize(100, 16777215))
        self.startingMapLabel.setObjectName("startingMapLabel")
        self.horizontalLayout.addWidget(self.startingMapLabel)
        self.startingMapDropdown = QtWidgets.QToolButton(self.scrollAreaWidgetContents)
        self.startingMapDropdown.setMinimumSize(QtCore.QSize(150, 0))
        self.startingMapDropdown.setPopupMode(QtWidgets.QToolButton.MenuButtonPopup)
        self.startingMapDropdown.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.startingMapDropdown.setObjectName("startingMapDropdown")
        self.horizontalLayout.addWidget(self.startingMapDropdown)
        self.startingScenarioDropdown = QtWidgets.QToolButton(self.scrollAreaWidgetContents)
        self.startingScenarioDropdown.setMinimumSize(QtCore.QSize(150, 0))
        self.startingScenarioDropdown.setPopupMode(QtWidgets.QToolButton.MenuButtonPopup)
        self.startingScenarioDropdown.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.startingScenarioDropdown.setObjectName("startingScenarioDropdown")
        self.horizontalLayout.addWidget(self.startingScenarioDropdown)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout_6.addLayout(self.horizontalLayout)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.mapsContainer.addWidget(self.scrollArea)
        self.toolsBox = QtWidgets.QGroupBox(self.maps)
        self.toolsBox.setObjectName("toolsBox")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.toolsBox)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setContentsMargins(-1, -1, -1, 0)
        self.verticalLayout_4.setSpacing(5)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.toggleVersusButton = QtWidgets.QPushButton(self.toolsBox)
        self.toggleVersusButton.setObjectName("toggleVersusButton")
        self.verticalLayout_4.addWidget(self.toggleVersusButton)
        self.toggleCoOpButton = QtWidgets.QPushButton(self.toolsBox)
        self.toggleCoOpButton.setObjectName("toggleCoOpButton")
        self.verticalLayout_4.addWidget(self.toggleCoOpButton)
        self.toggleLikeLastButton = QtWidgets.QPushButton(self.toolsBox)
        self.toggleLikeLastButton.setObjectName("toggleLikeLastButton")
        self.verticalLayout_4.addWidget(self.toggleLikeLastButton)
        self.line = QtWidgets.QFrame(self.toolsBox)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_4.addWidget(self.line)
        self.saveMapListAsButton = QtWidgets.QPushButton(self.toolsBox)
        self.saveMapListAsButton.setObjectName("saveMapListAsButton")
        self.verticalLayout_4.addWidget(self.saveMapListAsButton)
        self.saveMapListButton = QtWidgets.QPushButton(self.toolsBox)
        self.saveMapListButton.setObjectName("saveMapListButton")
        self.verticalLayout_4.addWidget(self.saveMapListButton)
        self.line_2 = QtWidgets.QFrame(self.toolsBox)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_4.addWidget(self.line_2)
        self.loadMapListButton = QtWidgets.QPushButton(self.toolsBox)
        self.loadMapListButton.setObjectName("loadMapListButton")
        self.verticalLayout_4.addWidget(self.loadMapListButton)
        self.label = QtWidgets.QLabel(self.toolsBox)
        self.label.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label.setObjectName("label")
        self.verticalLayout_4.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self.toolsBox)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_4.addWidget(self.label_2)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem1)
        self.verticalLayout_5.addLayout(self.verticalLayout_4)
        self.mapsContainer.addWidget(self.toolsBox)
        self.verticalLayout_3.addLayout(self.mapsContainer)
        self.mainTabs.addTab(self.maps, "")
        self.verticalLayout.addWidget(self.mainTabs)
        self.serverStatusBar = QtWidgets.QHBoxLayout()
        self.serverStatusBar.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.serverStatusBar.setContentsMargins(-1, 10, -1, -1)
        self.serverStatusBar.setObjectName("serverStatusBar")
        self.serverStatusLabel = QtWidgets.QLabel(self.centralwidget)
        self.serverStatusLabel.setMinimumSize(QtCore.QSize(62, 0))
        self.serverStatusLabel.setMaximumSize(QtCore.QSize(62, 16777215))
        self.serverStatusLabel.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.serverStatusLabel.setObjectName("serverStatusLabel")
        self.serverStatusBar.addWidget(self.serverStatusLabel)
        self.serverStatus = QtWidgets.QLabel(self.centralwidget)
        self.serverStatus.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.serverStatus.setFont(font)
        self.serverStatus.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.serverStatus.setObjectName("serverStatus")
        self.serverStatusBar.addWidget(self.serverStatus)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.serverStatusBar.addItem(spacerItem2)
        self.startServerButton = QtWidgets.QPushButton(self.centralwidget)
        self.startServerButton.setMinimumSize(QtCore.QSize(150, 0))
        self.startServerButton.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.startServerButton.setObjectName("startServerButton")
        self.serverStatusBar.addWidget(self.startServerButton)
        self.verticalLayout.addLayout(self.serverStatusBar)
        Inservency.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Inservency)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 796, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        self.menuServer = QtWidgets.QMenu(self.menubar)
        self.menuServer.setObjectName("menuServer")
        Inservency.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Inservency)
        self.statusbar.setObjectName("statusbar")
        Inservency.setStatusBar(self.statusbar)
        self.actionSave_Settings = QtWidgets.QAction(Inservency)
        self.actionSave_Settings.setObjectName("actionSave_Settings")
        self.actionLoad_Settings = QtWidgets.QAction(Inservency)
        self.actionLoad_Settings.setObjectName("actionLoad_Settings")
        self.actionSave_Map_List = QtWidgets.QAction(Inservency)
        self.actionSave_Map_List.setObjectName("actionSave_Map_List")
        self.actionLoad_Map_List = QtWidgets.QAction(Inservency)
        self.actionLoad_Map_List.setObjectName("actionLoad_Map_List")
        self.actionStart_Server = QtWidgets.QAction(Inservency)
        self.actionStart_Server.setObjectName("actionStart_Server")
        self.actionStop_Server = QtWidgets.QAction(Inservency)
        self.actionStop_Server.setObjectName("actionStop_Server")
        self.actionRestart_Server = QtWidgets.QAction(Inservency)
        self.actionRestart_Server.setObjectName("actionRestart_Server")
        self.actionSave_Map_List_as = QtWidgets.QAction(Inservency)
        self.actionSave_Map_List_as.setObjectName("actionSave_Map_List_as")
        self.menuFile.addAction(self.actionSave_Settings)
        self.menuFile.addAction(self.actionLoad_Settings)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionSave_Map_List)
        self.menuFile.addAction(self.actionSave_Map_List_as)
        self.menuFile.addAction(self.actionLoad_Map_List)
        self.menuServer.addAction(self.actionStart_Server)
        self.menuServer.addAction(self.actionStop_Server)
        self.menuServer.addAction(self.actionRestart_Server)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuServer.menuAction())

        self.retranslateUi(Inservency)
        self.mainTabs.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(Inservency)

    def retranslateUi(self, Inservency):
        _translate = QtCore.QCoreApplication.translate
        Inservency.setWindowTitle(_translate("Inservency", "Inservency"))
        self.mainTabs.setToolTip(_translate("Inservency", "<html><head/><body><p>Remote connection settings</p></body></html>"))
        self.serverNameLabel.setText(_translate("Inservency", "Server Name"))
        self.serverNameEdit.setText(_translate("Inservency", "Inservency Server"))
        self.queryPortLabel.setText(_translate("Inservency", "Query Port"))
        self.passwordLabel.setText(_translate("Inservency", "Password"))
        self.maxPlayersLabel.setText(_translate("Inservency", "Max Players"))
        self.cheatsLabel.setText(_translate("Inservency", "Cheats"))
        self.motdLabel.setText(_translate("Inservency", "MOTD"))
        self.gamePortInput.setToolTip(_translate("Inservency", "Port that the game will listen. Make sure this is port forwarded in your router."))
        self.queryPortInput.setToolTip(_translate("Inservency", "Query port for the server. Make sure this is port forwarded in your router."))
        self.checkBox.setText(_translate("Inservency", "Enable Cheats"))
        self.plainTextEdit.setPlainText(_translate("Inservency", "Welcome to the server!"))
        self.gamePortLabel.setText(_translate("Inservency", "Game Port"))
        self.mainTabs.setTabText(self.mainTabs.indexOf(self.basicSetup), _translate("Inservency", "Settings"))
        self.mainTabs.setTabToolTip(self.mainTabs.indexOf(self.basicSetup), _translate("Inservency", "Basic settings for your server."))
        self.startingMapLabel.setText(_translate("Inservency", "Starting Map:"))
        self.startingMapDropdown.setText(_translate("Inservency", "Select Map...", "0"))
        self.startingScenarioDropdown.setText(_translate("Inservency", "Select Scenario..."))
        self.toolsBox.setTitle(_translate("Inservency", "Tools"))
        self.toggleVersusButton.setText(_translate("Inservency", "Toggle all versus scenarios"))
        self.toggleCoOpButton.setText(_translate("Inservency", "Toggle all co-op scenarios"))
        self.toggleLikeLastButton.setToolTip(_translate("Inservency", "Enable or disable all scenarios like the last one that was edited. For instance, if you disabled a Checkpoint Insurgents scenario, all Checkpoint Insurgents scenarios will be disabled."))
        self.toggleLikeLastButton.setText(_translate("Inservency", "Toggle all like last scenario"))
        self.saveMapListAsButton.setText(_translate("Inservency", "Save As New Map List"))
        self.saveMapListButton.setText(_translate("Inservency", "Save Changes"))
        self.loadMapListButton.setText(_translate("Inservency", "Load Map List"))
        self.label.setText(_translate("Inservency", "Open Map List:"))
        self.label_2.setText(_translate("Inservency", "None"))
        self.mainTabs.setTabText(self.mainTabs.indexOf(self.maps), _translate("Inservency", "Maps"))
        self.mainTabs.setTabToolTip(self.mainTabs.indexOf(self.maps), _translate("Inservency", "Map list and initial map management."))
        self.serverStatusLabel.setText(_translate("Inservency", "Server Status:"))
        self.serverStatus.setText(_translate("Inservency", "Offline"))
        self.startServerButton.setText(_translate("Inservency", "Start Server"))
        self.menuFile.setTitle(_translate("Inservency", "File"))
        self.menuEdit.setTitle(_translate("Inservency", "Edit"))
        self.menuServer.setTitle(_translate("Inservency", "Server"))
        self.actionSave_Settings.setText(_translate("Inservency", "Save Settings..."))
        self.actionLoad_Settings.setText(_translate("Inservency", "Load Settings..."))
        self.actionSave_Map_List.setText(_translate("Inservency", "Save Map List..."))
        self.actionLoad_Map_List.setText(_translate("Inservency", "Load Map List..."))
        self.actionStart_Server.setText(_translate("Inservency", "Start Server"))
        self.actionStart_Server.setToolTip(_translate("Inservency", "Start the Insurgency: Sandstorm server"))
        self.actionStop_Server.setText(_translate("Inservency", "Stop Server"))
        self.actionRestart_Server.setText(_translate("Inservency", "Restart Server"))
        self.actionSave_Map_List_as.setText(_translate("Inservency", "Save Map List as..."))

